[package]
name = "generative-art-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.12.0"
image = "0.24.6"
imageproc = "0.23.0"
minimp4 = "0.1.0"
openh264 = "0.4.1"